/** @type {import('tailwindcss').Config} */
export default {
  future: {
    hoverOnlyWhenSupported: true,
  },
  content: [
    "./index.html",
    "./*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./services/**/*.{js,ts,jsx,tsx}",
    "./hooks/**/*.{js,ts,jsx,tsx}",
    "./store/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        display: ['Space Grotesk', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        outfit: ['Outfit', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
      },
      colors: {
        brand: {
          50: '#f3e8ff',
          100: '#e9d5ff',
          200: '#d8b4fe',
          300: '#c084fc',
          400: '#a78bfa',
          500: '#8b5cf6',
          600: '#7c3aed',
          700: '#6d28d9',
          800: '#5b21b6',
          900: '#4c1d95',
          DEFAULT: '#7c3aed',
        },
        accent: {
          DEFAULT: '#00c4cc',
          light: '#33d4db',
          dark: '#00a8af',
          hover: '#00b3b8',
        },
        surface: {
          0: '#ffffff',
          1: '#f8f9fa',
          2: '#f1f3f5',
          3: '#e9ecef',
          4: '#dee2e6',
          5: '#ced4da',
          'dark-0': '#0d0d12',
          'dark-1': '#111118',
          'dark-2': '#16161e',
          'dark-3': '#1e1e28',
          'dark-4': '#252530',
          'dark-5': '#2e2e3a',
        },
        muted: {
          DEFAULT: '#9ca3af',
          light: '#d1d5db',
          dark: '#6b7280',
        },
        success: { DEFAULT: '#34d399', light: '#6ee7b7', dark: '#059669' },
        warning: { DEFAULT: '#fbbf24', light: '#fcd34d', dark: '#d97706' },
        error: { DEFAULT: '#f87171', light: '#fca5a5', dark: '#dc2626' },
        info: { DEFAULT: '#60a5fa', light: '#93c5fd', dark: '#2563eb' },
      },
      boxShadow: {
        'glow-brand': '0 4px 20px rgba(124, 58, 237, 0.15)',
        'glow-accent': '0 4px 20px rgba(0, 196, 204, 0.15)',
        'inner-glow': 'inset 0 1px 0 rgba(255, 255, 255, 0.06)',
        'elevated': '0 4px 12px rgba(0, 0, 0, 0.3)',
        'elevated-lg': '0 8px 24px rgba(0, 0, 0, 0.4)',
        'surface': '0 1px 3px rgba(0, 0, 0, 0.2)',
      },
      zIndex: {
        'base': '0',
        'raised': '10',
        'dropdown': '50',
        'sticky': '100',
        'modal-backdrop': '150',
        'modal': '200',
        'popover': '250',
        'tooltip': '300',
        'overlay': '400',
        'toast': '500',
      },
      transitionDuration: {
        '250': '250ms',
        '400': '400ms',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(4px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-6px)' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
      animation: {
        'fade-in': 'fade-in 200ms ease-out',
        'slide-up': 'slide-up 250ms ease-out',
        'scale-in': 'scale-in 200ms ease-out',
        'pulse-soft': 'pulse-soft 2s ease-in-out infinite',
        'float': 'float 6s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
      },
    },
  },
  plugins: [],
}
