import { Artboard, Layer } from '../../../types';
import { v4 as uuidv4 } from 'uuid';

export const createNebulaDemoDesign = (): Artboard => {
  const artboardId = 'nebula_demo';
  const layers: Layer[] = [
    // Background Decoration 1
    {
      id: uuidv4(),
      type: 'shape',
      name: 'Nebula Glow Left',
      x: -200,
      y: -100,
      width: 600,
      height: 600,
      rotation: 0,
      opacity: 0.4,
      visible: true,
      locked: true,
      shapeType: 'ellipse',
      fill: { color: '#7d2ae8', opacity: 0.3 },
      filters: { blur: 120 }
    } as any,
    // Background Decoration 2
    {
      id: uuidv4(),
      type: 'shape',
      name: 'Nebula Glow Right',
      x: 700,
      y: 300,
      width: 500,
      height: 500,
      rotation: 0,
      opacity: 0.3,
      visible: true,
      locked: true,
      shapeType: 'ellipse',
      fill: { color: '#00f2ff', opacity: 0.2 },
      filters: { blur: 100 }
    } as any,
    // Navbar Logo
    {
      id: uuidv4(),
      type: 'text',
      name: 'Logo',
      x: 60,
      y: 40,
      width: 200,
      height: 40,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: 'NEBULA',
      fontSize: 24,
      fontFamily: 'Inter',
      fontWeight: '900',
      fontStyle: 'normal',
      textDecoration: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      textTransform: 'none',
      color: '#ffffff',
      textAlign: 'left'
    } as any,
    // Hero Title
    {
      id: uuidv4(),
      type: 'text',
      name: 'Hero Title',
      x: 60,
      y: 200,
      width: 760,
      height: 160,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: 'Next-Gen Banking for the Digital Frontier',
      fontSize: 82,
      fontFamily: 'Inter',
      fontWeight: '800',
      fontStyle: 'normal',
      textDecoration: 'none',
      letterSpacing: -2,
      lineHeight: 1.1,
      textTransform: 'none',
      color: '#ffffff',
      textAlign: 'left'
    } as any,
    // Hero Subtitle
    {
      id: uuidv4(),
      type: 'text',
      name: 'Hero Subtitle',
      x: 60,
      y: 380,
      width: 600,
      height: 80,
      rotation: 0,
      opacity: 0.7,
      visible: true,
      locked: false,
      text: 'Experience the world\'s first intelligent, multi-agent financial dashboard. Elegant, secure, and futuristic.',
      fontSize: 20,
      fontFamily: 'Inter',
      fontWeight: '400',
      fontStyle: 'normal',
      textDecoration: 'none',
      letterSpacing: 0,
      lineHeight: 1.5,
      textTransform: 'none',
      color: '#a1a1aa',
      textAlign: 'left'
    } as any,
    // CTA Button Background
    {
      id: uuidv4(),
      type: 'shape',
      name: 'CTA Button',
      x: 60,
      y: 490,
      width: 200,
      height: 60,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      shapeType: 'rectangle',
      cornerRadius: 12,
      fill: { color: '#7d2ae8', opacity: 1 },
      stroke: { color: '#ffffff', width: 0, opacity: 0 }
    } as any,
    // CTA Button Text
    {
      id: uuidv4(),
      type: 'text',
      name: 'CTA Text',
      x: 95,
      y: 508,
      width: 130,
      height: 24,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: true,
      text: 'GET STARTED',
      fontSize: 16,
      fontFamily: 'Inter',
      fontWeight: '700',
      fontStyle: 'normal',
      textDecoration: 'none',
      letterSpacing: 1,
      lineHeight: 1,
      textTransform: 'uppercase',
      color: '#ffffff',
      textAlign: 'center'
    } as any,
    // Glass Card Background
    {
      id: uuidv4(),
      type: 'shape',
      name: 'Glass Card',
      x: 750,
      y: 200,
      width: 400,
      height: 260,
      rotation: -5,
      opacity: 1,
      visible: true,
      locked: false,
      shapeType: 'rectangle',
      cornerRadius: 24,
      fill: { color: '#ffffff', opacity: 0.05 },
      stroke: { color: '#ffffff', width: 1, opacity: 0.2 },
      filters: { backdropBlur: 20, blur: 0, brightness: 100, contrast: 100, saturation: 100, grayscale: 0, sepia: 0, hueRotate: 0, opacity: 1 }
    } as any,
    // Card Balance Title
    {
      id: uuidv4(),
      type: 'text',
      name: 'Card Balance Title',
      x: 790,
      y: 250,
      width: 200,
      height: 20,
      rotation: -5,
      opacity: 0.5,
      visible: true,
      locked: true,
      text: 'CURRENT BALANCE',
      fontSize: 14,
      fontFamily: 'Inter',
      fontWeight: '600',
      fontStyle: 'normal',
      textDecoration: 'none',
      letterSpacing: 1,
      lineHeight: 1,
      textTransform: 'uppercase',
      color: '#ffffff',
      textAlign: 'left'
    } as any,
    // Card Balance Amount
    {
      id: uuidv4(),
      type: 'text',
      name: 'Balance Amount',
      x: 790,
      y: 285,
      width: 320,
      height: 60,
      rotation: -5,
      opacity: 1,
      visible: true,
      locked: true,
      text: '$42,500.00',
      fontSize: 48,
      fontFamily: 'Inter',
      fontWeight: '700',
      fontStyle: 'normal',
      textDecoration: 'none',
      letterSpacing: -1,
      lineHeight: 1,
      textTransform: 'none',
      color: '#ffffff',
      textAlign: 'left'
    } as any,
    // Card Chips/Elements
    {
      id: uuidv4(),
      type: 'shape',
      name: 'Card Glow',
      x: 1000,
      y: 230,
      width: 100,
      height: 100,
      rotation: 0,
      opacity: 0.4,
      visible: true,
      locked: true,
      shapeType: 'ellipse',
      fill: { color: '#00f2ff', opacity: 0.4 },
      filters: { blur: 40 }
    } as any,
  ];

  return {
    id: artboardId,
    name: 'Nebula Hero Design',
    x: 0,
    y: 0,
    width: 1200,
    height: 800,
    backgroundColor: '#09090b',
    layers
  };
};
