import { log } from '../utils/log';
import { Artboard, Layer } from '../types';
import { v4 as uuidv4 } from 'uuid';

export interface TemplateMetadata {
  id: string;
  name: string;
  description: string;
  category: string;
  tags: string[];
  author: string;
  downloads: number;
  likes: number;
  thumbnailUrl?: string;
  layers: Layer[];
  width: number;
  height: number;
}

const TEMPLATES_STORAGE_KEY = 'kreathief_community_templates';

// In a real app, this would be an API call to a backend database (e.g., Supabase)
export class TemplateService {
  /**
   * Retrieves all community templates, potentially filtered by category.
   */
  static async getCommunityTemplates(category?: string): Promise<TemplateMetadata[]> {
    try {
      // Simulate network delay
      await new Promise(resolve => setTimeout(resolve, 800));
      
      const stored = localStorage.getItem(TEMPLATES_STORAGE_KEY);
      let templates: TemplateMetadata[] = stored ? JSON.parse(stored) : this.getMockTemplates();
      
      if (category && category !== 'All') {
        templates = templates.filter(t => t.category.toLowerCase() === category.toLowerCase());
      }
      
      return templates;
    } catch (error) {
      log.error('Failed to get community templates', error);
      return [];
    }
  }

  /**
   * Submits a local artboard to the community marketplace.
   */
  static async submitTemplate(artboard: Artboard, metadata: Partial<TemplateMetadata>): Promise<boolean> {
    try {
      // Simulate upload delay
      await new Promise(resolve => setTimeout(resolve, 1500));
      
      const stored = localStorage.getItem(TEMPLATES_STORAGE_KEY);
      const templates: TemplateMetadata[] = stored ? JSON.parse(stored) : this.getMockTemplates();
      
      const newTemplate: TemplateMetadata = {
        id: uuidv4(),
        name: metadata.name || 'Untitled Template',
        description: metadata.description || '',
        category: metadata.category || 'General',
        tags: metadata.tags || [],
        author: metadata.author || 'Anonymous Creator',
        downloads: 0,
        likes: 0,
        thumbnailUrl: metadata.thumbnailUrl || '', // Base64 thumbnail would go here
        layers: artboard.layers,
        width: artboard.width,
        height: artboard.height,
      };
      
      templates.unshift(newTemplate);
      localStorage.setItem(TEMPLATES_STORAGE_KEY, JSON.stringify(templates));
      
      log.info('Template submitted successfully', newTemplate.id);
      return true;
    } catch (error) {
      log.error('Failed to submit template', error);
      return false;
    }
  }

  /**
   * Mocks a request to Gemini to generate a template based on a prompt.
   * In a full implementation, this would call geminiService.
   */
  static async generateTemplateWithAI(prompt: string, width: number, height: number): Promise<TemplateMetadata> {
    try {
      log.info('Generating AI template for prompt:', prompt);
      // Simulate heavy AI processing delay
      await new Promise(resolve => setTimeout(resolve, 3000));
      
      // We return a hard-coded mocked response for safety,
      // but ideally this parses a JSON response from Gemini into Kreathief Layers.
      const generatedLayers: Layer[] = [
        {
          id: uuidv4(),
          type: 'rectangle',
          name: 'AI Background',
          x: 0,
          y: 0,
          width,
          height,
          color: '#1a1a1a',
          rotation: 0,
          opacity: 100,
          blendMode: 'normal',
          locked: true,
          hidden: false
        } as any,
        {
          id: uuidv4(),
          type: 'text',
          name: 'AI Headline',
          x: width * 0.1,
          y: height * 0.4,
          width: width * 0.8,
          height: 100,
          text: prompt.toUpperCase(),
          fontFamily: 'Inter',
          fontSize: 64,
          color: '#ffffff',
          fontWeight: 'bold',
          textAlign: 'center',
          rotation: 0,
          opacity: 100,
          blendMode: 'normal',
          locked: false,
          hidden: false
        } as any
      ];

      return {
        id: uuidv4(),
        name: `AI Gen: ${prompt}`,
        description: 'Generated by Kreathief AI Design Agent',
        category: 'AI Generated',
        tags: ['ai', 'generated'],
        author: 'Kreathief AI',
        downloads: 0,
        likes: 0,
        layers: generatedLayers,
        width,
        height
      };
    } catch (error) {
      log.error('AI Template Generation failed', error);
      throw error;
    }
  }

  private static getMockTemplates(): TemplateMetadata[] {
    return [
      {
        id: 'mock-1',
        name: 'Neon Cyberpunk UI',
        description: 'A dark, neon-infused UI layout perfect for gaming streams.',
        category: 'Social Media',
        tags: ['neon', 'cyberpunk', 'gaming'],
        author: 'Kreathief Team',
        downloads: 1250,
        likes: 340,
        width: 1080,
        height: 1080,
        layers: [] // Real layers would go here
      },
      {
        id: 'mock-2',
        name: 'Minimalist Fashion Brand',
        description: 'Clean typographic layout for fashion lookbooks.',
        category: 'Brand',
        tags: ['minimal', 'fashion', 'typography'],
        author: 'DesignPro',
        downloads: 840,
        likes: 120,
        width: 1080,
        height: 1350,
        layers: []
      }
    ];
  }
}
